name = "stabletweet"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-04-06"

kv_namespaces = [
	{ binding = "TWEET_EXISTS", preview_id = "4e852aa66b904e8bb45597494d39aa82", id = "677982c68fe04777b8cff7cdb30ea4cb" },
]
